package com.demonicrous.motionui.client;
import com.demonicrous.motionui.config.MotionUIConfig;import java.io.IOException;import java.util.*;import net.minecraft.client.gui.*;import net.minecraft.client.resources.I18n;
public final class GuiCatalogScreen extends GuiScreen{
 private static final int HEADER=52,ROW=24,GEAR=20;private final GuiScreen parent;private final List<GuiCatalog.Entry>visible=new ArrayList<GuiCatalog.Entry>();private GuiTextField search;private GuiButton sortButton,configuredButton;private String mod;private MotionUIConfig.CatalogSort sort;private boolean configuredOnly;private int offset,lastRevision=-1;
 public GuiCatalogScreen(GuiScreen p){parent=p;mod=MotionUIConfig.catalogMod;sort=MotionUIConfig.catalogSort;configuredOnly=MotionUIConfig.catalogConfiguredOnly;offset=MotionUIConfig.catalogScroll;}
 private int left(){return Math.max(8,(width-1000)/2);}private int right(){return Math.min(width-8,left()+1000);}private int header(){return compact()?76:HEADER;}private int rows(){return Math.max(1,(height-header()-34)/ROW);}
 public void initGui(){int sx=left()+(compact()?84:104),sw=compact()?Math.max(70,right()-sx-78):Math.max(70,right()-left()-394);search=new GuiTextField(3,fontRenderer,sx,27,sw,20);search.setMaxStringLength(120);search.setText(MotionUIConfig.catalogSearch);rebuild();}
 private void rebuild(){lastRevision=GuiCatalog.revision();String q=search==null?"":search.getText().toLowerCase(Locale.ROOT);visible.clear();for(GuiCatalog.Entry e:GuiCatalog.entries())if(("all".equals(mod)||mod.equals(e.modId))&&(!configuredOnly||MotionUIConfig.isConfigured(e.className))&&(q.isEmpty()||e.className.toLowerCase(Locale.ROOT).contains(q)))visible.add(e);Collections.sort(visible,comparator());offset=Math.max(0,Math.min(offset,Math.max(0,visible.size()-rows())));buttons();}
 private Comparator<GuiCatalog.Entry> comparator(){return new Comparator<GuiCatalog.Entry>(){public int compare(GuiCatalog.Entry a,GuiCatalog.Entry b){int c=0;if(sort==MotionUIConfig.CatalogSort.CONFIGURED)c=Boolean.compare(MotionUIConfig.isConfigured(b.className),MotionUIConfig.isConfigured(a.className));else if(sort==MotionUIConfig.CatalogSort.OBSERVED)c=Boolean.compare(b.observed,a.observed);if(c==0&&sort!=MotionUIConfig.CatalogSort.NAME)c=a.modId.compareToIgnoreCase(b.modId);return c!=0?c:a.className.compareToIgnoreCase(b.className);}};}
 private void buttons(){buttonList.clear();boolean c=compact();buttonList.add(new GuiButton(1,left(),27,c?80:96,20,I18n.format("motionui.catalog.mod",mod)));sortButton=new GuiButton(4,c?left():right()-282,c?51:27,c?120:100,20,I18n.format("motionui.catalog.sort."+sort.name().toLowerCase(Locale.ROOT)));buttonList.add(sortButton);configuredButton=new GuiButton(5,c?left()+124:right()-178,c?51:27,30,20,configuredOnly?"§e★":"☆");buttonList.add(configuredButton);buttonList.add(new GuiButton(2,right()-74,27,74,20,I18n.format("gui.done")));buttonList.add(new GuiButton(10,right()-226,height-24,104,20,I18n.format("motionui.catalog.settings")));buttonList.add(new GuiButton(11,right()-118,height-24,118,20,I18n.format("motionui.catalog.diagnostics")));for(int i=0;i<rows()&&offset+i<visible.size();i++)buttonList.add(new GuiButton(1000+i,right()-GEAR,header()+2+i*ROW,GEAR,20,"⚙"));}
 protected void actionPerformed(GuiButton b)throws IOException{if(b.id==2){save();mc.displayGuiScreen(parent);}else if(b.id==10){save();mc.displayGuiScreen(new GuiMotionUISettings(this));}else if(b.id==11){save();mc.displayGuiScreen(new GuiDiagnosticsScreen(this));}else if(b.id==1)cycleMod(1);else if(b.id==4)cycleSort(1);else if(b.id==5){configuredOnly=!configuredOnly;offset=0;rebuild();}else if(b.id>=1000){int i=offset+b.id-1000;if(i<visible.size()){save();mc.displayGuiScreen(new GuiScreenRuleEditor(this,visible.get(i)));}}}
 private void cycleMod(int direction){List<String>ids=new ArrayList<String>();ids.add("all");for(GuiCatalog.Entry e:GuiCatalog.entries())if(!ids.contains(e.modId))ids.add(e.modId);if(ids.size()>1)Collections.sort(ids.subList(1,ids.size()));int i=ids.indexOf(mod);if(i<0)i=0;mod=ids.get((i+(direction<0?ids.size()-1:1))%ids.size());offset=0;rebuild();}
 private void cycleSort(int direction){MotionUIConfig.CatalogSort[]v=MotionUIConfig.CatalogSort.values();sort=v[(sort.ordinal()+(direction<0?v.length-1:1))%v.length];offset=0;rebuild();}
 private void save(){MotionUIConfig.saveCatalogState(search==null?"":search.getText(),mod,sort,configuredOnly,offset);}public void onGuiClosed(){save();}
 protected void keyTyped(char c,int k)throws IOException{if(k==1){save();mc.displayGuiScreen(parent);return;}if(search.textboxKeyTyped(c,k)){offset=0;rebuild();}}
 protected void mouseClicked(int x,int y,int b)throws IOException{search.mouseClicked(x,y,b);if(b==1){GuiButton hit=buttonAt(x,y);if(hit!=null){if(hit.id==1){cycleMod(-1);return;}if(hit.id==4){cycleSort(-1);return;}if(hit.id==5){configuredOnly=!configuredOnly;offset=0;rebuild();return;}}}super.mouseClicked(x,y,b);}private GuiButton buttonAt(int x,int y){for(GuiButton q:buttonList)if(q.visible&&q.enabled&&over(q,x,y))return q;return null;}public void handleMouseInput()throws IOException{super.handleMouseInput();int w=org.lwjgl.input.Mouse.getEventDWheel();if(w!=0){offset+=w<0?3:-3;rebuild();}}public void updateScreen(){search.updateCursorCounter();if(lastRevision!=GuiCatalog.revision())rebuild();}
 public void drawScreen(int mx,int my,float p){int h=header();drawDefaultBackground();drawRect(0,0,width,h,0xCC101820);drawCenteredString(fontRenderer,I18n.format("motionui.catalog.title"),width/2,9,0xFFFFFF);search.drawTextBox();if(search.getText().isEmpty()&&!search.isFocused())drawString(fontRenderer,I18n.format("motionui.catalog.searchHint"),search.x+5,34,0x777777);for(int i=0;i<rows()&&offset+i<visible.size();i++){GuiCatalog.Entry e=visible.get(offset+i);int y=h+i*ROW;drawRect(left(),y,right(),y+ROW-1,(i&1)==0?0x77242C35:0x77303943);drawString(fontRenderer,(e.observed?"§a●":"§7○")+" §b"+e.modId+"§r  "+shortName(e.className),left()+6,y+8,0xE0E0E0);String state=opening(e.className)+"   "+closing(e.className);drawString(fontRenderer,state,right()-GEAR-8-fontRenderer.getStringWidth(state),y+8,0xDDDDDD);}if(visible.isEmpty())drawCenteredString(fontRenderer,I18n.format("motionui.catalog.empty"),width/2,height/2,0xAAAAAA);if(!visible.isEmpty())drawString(fontRenderer,(offset+1)+"–"+Math.min(visible.size(),offset+rows())+" / "+visible.size(),left(),height-14,0x999999);super.drawScreen(mx,my,p);if(over(sortButton,mx,my)){String key="motionui.catalog.sortHint."+sort.name().toLowerCase(Locale.ROOT);TextTooltip.draw(fontRenderer,I18n.format("motionui.catalog.sortHint.title"),I18n.format(key),mx,my,width,height);return;}if(over(configuredButton,mx,my)){String key=configuredOnly?"motionui.catalog.configuredHint.on":"motionui.catalog.configuredHint.off";TextTooltip.draw(fontRenderer,I18n.format("motionui.catalog.configuredHint.title"),I18n.format(key),mx,my,width,height);return;}int row=(my-h)/ROW;if(my>=h&&row>=0&&row<rows()&&offset+row<visible.size()&&mx>right()-360){GuiCatalog.Entry e=visible.get(offset+row);TextTooltip.draw(fontRenderer,"§e§l"+shortName(e.className)+"§r",tooltip(e.className),mx,my,width,height);}}
 private static boolean over(GuiButton b,int x,int y){return b!=null&&x>=b.x&&x<b.x+b.width&&y>=b.y&&y<b.y+b.height;}
 private boolean compact(){return right()-left()<600;}private String opening(String n){MotionUIConfig.Policy p=MotionUIConfig.policy(n);if(compact())return p==MotionUIConfig.Policy.DISABLED?"§cO:×":p==MotionUIConfig.Policy.ENABLED||MotionUIConfig.hasRule(n)?"§eO:●":"§7O:↳";if(p==MotionUIConfig.Policy.DISABLED)return "§c"+I18n.format("motionui.catalog.open.disabled");if(p==MotionUIConfig.Policy.ENABLED||MotionUIConfig.hasRule(n))return "§e"+I18n.format("motionui.catalog.open.custom");return "§7"+I18n.format("motionui.catalog.open.inherit",profile());}private String closing(String n){MotionUIConfig.ClosingRule r=MotionUIConfig.closingRule(n);String m=I18n.format("motionui.closingMode."+r.mode.name().toLowerCase(Locale.ROOT));if(compact())return (MotionUIConfig.hasClosingRule(n)?"§eC:":"§7C:↳")+(r.mode==MotionUIConfig.ClosingMode.DISABLED?"×":r.mode==MotionUIConfig.ClosingMode.SIMPLIFIED?"S":"F");return (MotionUIConfig.hasClosingRule(n)?"§e"+I18n.format("motionui.catalog.close.custom",m):"§7"+I18n.format("motionui.catalog.close.inherit",m));}private String tooltip(String n){MotionUIConfig.ScreenRule o=MotionUIConfig.rule(n);MotionUIConfig.ClosingRule c=MotionUIConfig.closingRule(n);String op=MotionUIConfig.policy(n)==MotionUIConfig.Policy.DEFAULT&&!MotionUIConfig.hasRule(n)?"↳ ":"";String cl=MotionUIConfig.hasClosingRule(n)?"":"↳ ";return I18n.format("motionui.catalog.ruleTooltip",op+I18n.format("motionui.editor.opening"),o.duration,o.offset,cl+I18n.format("motionui.closingMode."+c.mode.name().toLowerCase(Locale.ROOT)),c.duration,c.offset);}private String profile(){return I18n.format("motionui.profile."+MotionUIConfig.profile().name().toLowerCase(Locale.ROOT));}private static String shortName(String n){int i=n.lastIndexOf('.');return i<0?n:n.substring(i+1);}public boolean doesGuiPauseGame(){return false;}
}
