package com.demonicrous.motionui.client;
import com.demonicrous.motionui.MotionUI;import com.demonicrous.motionui.config.MotionUIConfig;import com.demonicrous.motionui.core.*;import java.io.*;import java.lang.reflect.Method;import java.util.*;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.*;import net.minecraft.client.resources.IResource;import net.minecraft.client.resources.I18n;import net.minecraft.launchwrapper.Launch;import net.minecraft.util.ResourceLocation;import net.minecraftforge.common.ForgeVersion;
public final class GuiDiagnosticsScreen extends GuiScreen{
 private final GuiScreen parent;private boolean details;private String copied="";public GuiDiagnosticsScreen(GuiScreen p){parent=p;}
 public void initGui(){refresh();}private void refresh(){buttonList.clear();int x=width/2-140;buttonList.add(new GuiButton(1,x,height-52,88,20,I18n.format(details?"motionui.diagnostics.less":"motionui.diagnostics.more")));buttonList.add(new GuiButton(2,x+96,height-52,120,20,I18n.format("motionui.diagnostics.copy")));buttonList.add(new GuiButton(3,x+224,height-52,56,20,I18n.format("gui.done")));}
 protected void actionPerformed(GuiButton b)throws IOException{if(b.id==1){details=!details;refresh();}else if(b.id==2){GuiScreen.setClipboardString(report());copied=I18n.format("motionui.diagnostics.copied");}else if(b.id==3)mc.displayGuiScreen(parent);}
 protected void mouseClicked(int x,int y,int button)throws IOException{if(button==1){for(GuiButton b:buttonList)if(b.id==1&&x>=b.x&&x<b.x+b.width&&y>=b.y&&y<b.y+b.height){details=!details;refresh();return;}}super.mouseClicked(x,y,button);}
 public void drawScreen(int mx,int my,float p){drawDefaultBackground();drawCenteredString(fontRenderer,I18n.format("motionui.diagnostics.title"),width/2,18,0xFFFFFF);int x=Math.max(12,width/2-210),y=44;drawString(fontRenderer,"§fMinecraft 1.12.2  §7·  §fForge "+ForgeVersion.getVersion()+"  §7·  §fOptiFine "+optifine(),x,y,0xFFFFFF);y+=16;Map<String,PatchDiagnostics.Result> patches=PatchDiagnostics.snapshot();int warnings=warnings(patches);drawString(fontRenderer,(warnings==0?"§a":"§e")+I18n.format("motionui.diagnostics.patchSummary",patches.size()-warnings,patches.size()),x,y,0xFFFFFF);y+=16;String font=fontProvider("textures/font/unicode_page_04.png");boolean overridden=!font.toLowerCase(Locale.ROOT).contains("motionui");drawString(fontRenderer,(overridden?"§e":"§a")+I18n.format(overridden?"motionui.diagnostics.fontOverridden":"motionui.diagnostics.fontActive",font),x,y,0xFFFFFF);y+=18;if(details){for(Map.Entry<String,PatchDiagnostics.Result>e:patches.entrySet()){PatchDiagnostics.Result r=e.getValue();String color="APPLIED".equals(r.getStatus())?"§a":"FAILED".equals(r.getStatus())?"§c":"§e";drawString(fontRenderer,color+"● §f"+e.getKey()+" §7— "+r.getStatus(),x,y,0xFFFFFF);y+=12;drawString(fontRenderer,"   §8"+trim(r.getDetail(),72),x,y,0xFFFFFF);y+=14;}drawString(fontRenderer,"§7glyph_sizes.bin: §f"+fontProvider("font/glyph_sizes.bin"),x,y,0xFFFFFF);y+=14;drawString(fontRenderer,"§7unicode_page_04.png: §f"+font,x,y,0xFFFFFF);}if(!copied.isEmpty())drawCenteredString(fontRenderer,"§a"+copied,width/2,height-68,0xFFFFFF);super.drawScreen(mx,my,p);}
 private static int warnings(Map<String,PatchDiagnostics.Result>m){int n=0;for(PatchDiagnostics.Result r:m.values())if(!"APPLIED".equals(r.getStatus()))n++;return n;}private static String trim(String s,int n){return s.length()<=n?s:s.substring(0,n-1)+"…";}
 private static String optifine(){try{Class<?>c=Class.forName("Config",false,Launch.classLoader);Method m=c.getDeclaredMethod("getVersion");return String.valueOf(m.invoke(null));}catch(Throwable ignored){return I18n.format("motionui.diagnostics.notFound");}}
 private static String fontProvider(String path){IResource r=null;try{r=Minecraft.getMinecraft().getResourceManager().getResource(new ResourceLocation("minecraft",path));return r.getResourcePackName();}catch(Exception e){return I18n.format("motionui.diagnostics.unknown");}finally{if(r!=null)try{r.close();}catch(IOException ignored){}}}
 private static String report(){StringBuilder b=new StringBuilder();b.append("MotionUI ").append(MotionUI.VERSION).append('\n').append("Minecraft 1.12.2\nForge ").append(ForgeVersion.getVersion()).append("\nOptiFine ").append(optifine()).append("\nProfile ").append(MotionUIConfig.profile()).append("\nClosing ").append(MotionUIConfig.closingMode()).append("\nFont glyph_sizes.bin: ").append(fontProvider("font/glyph_sizes.bin")).append("\nFont unicode_page_04.png: ").append(fontProvider("textures/font/unicode_page_04.png")).append("\nResource packs: ").append(Minecraft.getMinecraft().gameSettings.resourcePacks).append("\nASM patches:\n");for(Map.Entry<String,PatchDiagnostics.Result>e:PatchDiagnostics.snapshot().entrySet())b.append("- ").append(e.getKey()).append(": ").append(e.getValue().getStatus()).append(" (").append(e.getValue().getDetail()).append(")\n");List<String>third=CompatibilityDiagnostics.thirdPartyTransformerClassNames();if(!third.isEmpty())b.append("Third-party transformers: ").append(third).append('\n');return b.toString();}
 protected void keyTyped(char c,int k)throws IOException{if(k==1){mc.displayGuiScreen(parent);return;}super.keyTyped(c,k);}public boolean doesGuiPauseGame(){return false;}
}
