package com.demonicrous.motionui.client;

import com.demonicrous.motionui.config.MotionUIConfig;
import java.util.*;
import net.minecraft.block.Block;
import net.minecraft.block.properties.IProperty;
import net.minecraft.block.state.IBlockState;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.FontRenderer;
import net.minecraft.client.gui.Gui;
import net.minecraft.client.multiplayer.ServerData;
import net.minecraft.client.network.NetworkPlayerInfo;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.client.resources.I18n;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.RayTraceResult;
import net.minecraftforge.client.event.RenderGameOverlayEvent;
import net.minecraftforge.common.ForgeVersion;
import net.minecraftforge.fml.common.eventhandler.EventPriority;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.InputEvent;
import org.lwjgl.input.Keyboard;
import org.lwjgl.opengl.GL11;

/** Optional F3 replacement using the same cards, spacing and palette as the F8 catalog. */
public final class ModernDebugOverlayEvents {
 private static final int PAD=MotionUILayout.S8,LINE=11,HEADER=18,GAP=MotionUILayout.S4;
 private static final Gui DEBUG_GUI=new Gui();private static final MotionUITooltipPanel FRAME=new MotionUITooltipPanel();
 private final Minecraft mc=Minecraft.getMinecraft();private final FpsSampler fps=new FpsSampler();private final SystemSnapshot system=new SystemSnapshot();
 private long memoryUpdated,usedMemory,totalMemory,allocatedMemory;

 @SubscribeEvent(priority=EventPriority.HIGHEST) public void suppressVanillaDebug(RenderGameOverlayEvent.Pre e){if(MotionUIConfig.modernDebug&&!mc.gameSettings.showDebugProfilerChart&&e.getType()==RenderGameOverlayEvent.ElementType.DEBUG)e.setCanceled(true);}
 @SubscribeEvent public void debugProfileShortcut(InputEvent.KeyInputEvent e){int key=Keyboard.getEventKey();if(Keyboard.getEventKeyState()&&mc.gameSettings.showDebugInfo&&MotionUIConfig.modernDebug&&(key==Keyboard.KEY_LSHIFT||key==Keyboard.KEY_RSHIFT)&&Keyboard.isKeyDown(Keyboard.KEY_F3))MotionUIConfig.cycleDebugProfile();}
 @SubscribeEvent(priority=EventPriority.LOWEST) public void renderModernDebug(RenderGameOverlayEvent.Text e){if(!MotionUIConfig.modernDebug||!mc.gameSettings.showDebugInfo||mc.gameSettings.showDebugProfilerChart)return;e.setCanceled(true);long now=System.nanoTime();fps.sample(now);updateMemory(now);List<Section>left=leftSections(),right=rightSections();appendExternalText(left,e.getLeft());appendExternalText(right,e.getRight());FontRenderer font=mc.fontRenderer;int width=e.getResolution().getScaledWidth(),height=e.getResolution().getScaledHeight();MotionUILayout.Rect[]columns=ModernDebugLayout.columns(width,preferredWidth(font,left),preferredWidth(font,right));drawColumn(font,columns[0],left);drawColumn(font,columns[1],right);drawFooter(font,width,height);}

 private List<Section> leftSections(){MotionUIConfig.DebugProfile profile=MotionUIConfig.debugProfile();List<Section>result=new ArrayList<Section>();Section client=new Section("motionui.debug.section.client").row("Minecraft","1.12.2");if(profile!=MotionUIConfig.DebugProfile.COMPACT)client.row("Forge",ForgeVersion.getVersion());client.row("FPS",Integer.toString(Minecraft.getDebugFPS())).row(I18n.format("motionui.debug.label.averageFps"),fps.summary()).row(I18n.format("motionui.debug.label.ping"),ping()+" ms");result.add(client);
  if(mc.player!=null&&!mc.gameSettings.reducedDebugInfo){BlockPos p=new BlockPos(mc.player);Section position=new Section("motionui.debug.section.position").row("XYZ",String.format(Locale.ROOT,"%.2f / %.2f / %.2f",mc.player.posX,mc.player.posY,mc.player.posZ)).row("Block",p.getX()+" / "+p.getY()+" / "+p.getZ()).row("Chunk",(p.getX()>>4)+" / "+(p.getY()>>4)+" / "+(p.getZ()>>4)).row(I18n.format("motionui.debug.label.local"),(p.getX()&15)+" / "+(p.getY()&15)+" / "+(p.getZ()&15)).row(I18n.format("motionui.debug.label.region"),(p.getX()>>9)+" / "+(p.getZ()>>9)).row(I18n.format("motionui.debug.label.facing"),I18n.format("motionui.debug.facing."+mc.player.getHorizontalFacing().getName()));if(profile==MotionUIConfig.DebugProfile.COMPACT){while(position.rows.size()>3)position.rows.remove(position.rows.size()-2);}result.add(position);}
  if(mc.world!=null&&profile!=MotionUIConfig.DebugProfile.COMPACT){BlockPos p=mc.player==null?BlockPos.ORIGIN:new BlockPos(mc.player);Section world=new Section("motionui.debug.section.world").row(I18n.format("motionui.debug.label.dimension"),Integer.toString(mc.player==null?0:mc.player.dimension)).row(I18n.format("motionui.debug.label.day"),Long.toString(mc.world.getWorldTime()/24000L+1));if(mc.player!=null&&!mc.gameSettings.reducedDebugInfo)world.row(I18n.format("motionui.debug.label.biome"),mc.world.getBiome(p).getBiomeName()).row(I18n.format("motionui.debug.label.light"),Integer.toString(mc.world.getLight(p))).row(I18n.format("motionui.debug.label.surface"),Integer.toString(mc.world.getHeight(p).getY()));world.row(I18n.format("motionui.debug.label.difficulty"),mc.world.getDifficulty().name()).row(I18n.format("motionui.debug.label.entities"),Integer.toString(mc.world.loadedEntityList.size())).row(I18n.format("motionui.debug.label.chunks"),mc.world.getChunkProvider().makeString());result.add(world);}
  if(profile==MotionUIConfig.DebugProfile.FULL&&!mc.gameSettings.reducedDebugInfo){Section target=targetSection();if(target!=null)result.add(target);}return result;}

 private List<Section> rightSections(){MotionUIConfig.DebugProfile profile=MotionUIConfig.debugProfile();List<Section>result=new ArrayList<Section>();int percent=totalMemory==0?0:(int)(usedMemory*100/totalMemory),color=percent>=85?MotionUITheme.DANGER:percent>=70?MotionUITheme.WARNING:MotionUITheme.TEXT;String status=percent>=85?I18n.format("motionui.debug.memory.high"):percent>=70?I18n.format("motionui.debug.memory.warning"):I18n.format("motionui.debug.memory.normal");result.add(new Section("motionui.debug.section.performance").row(I18n.format("motionui.debug.label.memory"),usedMemory+" / "+totalMemory+" MB ("+percent+"%) · "+status,color).row(I18n.format("motionui.debug.label.allocated"),allocatedMemory+" MB"));
  if(profile!=MotionUIConfig.DebugProfile.COMPACT){result.add(new Section("motionui.debug.section.system").row("Java",system.java).row(I18n.format("motionui.debug.cpu"),system.cpu).row(I18n.format("motionui.debug.os"),system.os));result.add(new Section("motionui.debug.section.display").row(I18n.format("motionui.debug.resolution"),mc.displayWidth+" × "+mc.displayHeight).row(I18n.format("motionui.debug.vendor"),system.vendor).row("GPU",system.renderer));}
  if(profile==MotionUIConfig.DebugProfile.FULL){ServerData server=mc.getCurrentServerData();String name=mc.isSingleplayer()?I18n.format("motionui.debug.integrated"):server==null?I18n.format("motionui.diagnostics.unknown"):server.serverName;result.add(new Section("motionui.debug.section.connection").row(I18n.format("motionui.debug.server"),name).row(I18n.format("motionui.debug.label.ping"),ping()+" ms").row(I18n.format("motionui.debug.profileLabel"),profileName()));}return result;}

 private Section targetSection(){RayTraceResult hit=mc.objectMouseOver;if(hit==null||hit.typeOfHit!=RayTraceResult.Type.BLOCK)return null;BlockPos p=hit.getBlockPos();IBlockState state=mc.world.getBlockState(p);Block block=state.getBlock();String id=block.getRegistryName()==null?block.getLocalizedName():block.getRegistryName().toString();StringBuilder props=new StringBuilder();for(Map.Entry<IProperty<?>,Comparable<?>>entry:state.getProperties().entrySet()){if(props.length()>0)props.append(", ");props.append(entry.getKey().getName()).append('=').append(entry.getValue());}Section section=new Section("motionui.debug.section.target").row(I18n.format("motionui.debug.block"),id).row(I18n.format("motionui.debug.position"),p.getX()+" / "+p.getY()+" / "+p.getZ()).row(I18n.format("motionui.debug.properties"),props.length()==0?"—":props.toString()).row(I18n.format("motionui.debug.label.light"),Integer.toString(mc.world.getLight(p)));RayTraceResult fluid=mc.world.rayTraceBlocks(mc.player.getPositionEyes(1F),mc.player.getPositionEyes(1F).add(mc.player.getLook(1F).scale(5D)),true,false,false);if(fluid!=null&&fluid.typeOfHit==RayTraceResult.Type.BLOCK){IBlockState fluidState=mc.world.getBlockState(fluid.getBlockPos());if(fluidState.getMaterial().isLiquid()){Block fluidBlock=fluidState.getBlock();section.row(I18n.format("motionui.debug.liquid"),fluidBlock.getRegistryName()==null?fluidBlock.getLocalizedName():fluidBlock.getRegistryName().toString());}}return section;}
 private void updateMemory(long now){if(now-memoryUpdated<250000000L)return;Runtime r=Runtime.getRuntime();usedMemory=(r.totalMemory()-r.freeMemory())/1048576L;totalMemory=r.maxMemory()/1048576L;allocatedMemory=r.totalMemory()/1048576L;memoryUpdated=now;}
 private int ping(){NetworkPlayerInfo i=mc.getConnection()==null||mc.player==null?null:mc.getConnection().getPlayerInfo(mc.player.getUniqueID());return i==null?0:i.getResponseTime();}
 private String profileName(){return I18n.format("motionui.debug.profile."+MotionUIConfig.debugProfile().name().toLowerCase(Locale.ROOT));}
 private static void appendExternalText(List<Section>s,List<String>lines){List<Row>rows=new ArrayList<Row>();for(String line:lines)if(line!=null&&!line.trim().isEmpty())rows.add(new Row("",line,MotionUITheme.TEXT));if(!rows.isEmpty())s.add(new Section("motionui.debug.section.additional",rows));}
 private static int preferredWidth(FontRenderer f,List<Section>s){int width=248;for(Section section:s){width=Math.max(width,f.getStringWidth(I18n.format(section.title))+PAD*2+12);for(Row row:section.rows){int label=row.label.isEmpty()?0:Math.max(52,f.getStringWidth(row.label)+10);width=Math.max(width,label+f.getStringWidth(row.value)+PAD*2+12);}}return Math.min(380,width);}
 private static void drawColumn(FontRenderer f,MotionUILayout.Rect col,List<Section>s){int cardWidth=Math.max(1,col.width-12),total=12-GAP;for(Section section:s)total+=sectionHeight(section)+GAP;FRAME.drawPanel(col.x,col.y,col.right(),col.y+total,.58F);int y=col.y+6;for(Section section:s){int h=sectionHeight(section);MotionUILayout.Rect card=new MotionUILayout.Rect(col.x+6,y,cardWidth,h);MotionUITheme.card(DEBUG_GUI,card,.72F);f.drawStringWithShadow("§e"+I18n.format(section.title),card.x+PAD,card.y+6,MotionUITheme.TEXT);int ty=card.y+HEADER,labelWidth=labelWidth(f,section,card.width),vx=card.x+PAD+labelWidth;for(Row row:section.rows){int valueX=row.label.isEmpty()?card.x+PAD:vx,valueWidth=Math.max(1,card.right()-PAD-valueX);if(!row.label.isEmpty())f.drawStringWithShadow(ellipsize(f,row.label,labelWidth-5),card.x+PAD,ty,MotionUITheme.TEXT_MUTED);f.drawStringWithShadow(ellipsize(f,row.value,valueWidth),valueX,ty,row.color);ty+=LINE;}y+=h+GAP;}}
 private static int sectionHeight(Section section){return HEADER+section.rows.size()*LINE+PAD;}
 private static int labelWidth(FontRenderer f,Section section,int cardWidth){int width=0;for(Row row:section.rows)if(!row.label.isEmpty())width=Math.max(width,f.getStringWidth(row.label));return Math.max(52,Math.min(width+10,(cardWidth-PAD*2)*40/100));}
 private static String ellipsize(FontRenderer f,String text,int width){if(f.getStringWidth(text)<=width)return text;String dots="...";int contentWidth=Math.max(0,width-f.getStringWidth(dots));return f.trimStringToWidth(text,contentWidth)+dots;}
 private void drawFooter(FontRenderer f,int width,int height){String text=I18n.format("motionui.debug.footer",profileName());int w=f.getStringWidth(text)+16,x=(width-w)/2,y=Math.max(6,height-52);MotionUILayout.Rect r=new MotionUILayout.Rect(x,y-4,w,f.FONT_HEIGHT+8);MotionUITheme.card(DEBUG_GUI,r,.62F);f.drawStringWithShadow(text,x+8,y,MotionUITheme.TEXT_MUTED);}

 private static final class Section{final String title;final List<Row>rows;Section(String t){this(t,new ArrayList<Row>());}Section(String t,List<Row>r){title=t;rows=r;}Section row(String l,String v){return row(l,v,MotionUITheme.TEXT);}Section row(String l,String v,int c){rows.add(new Row(l,v,c));return this;}}
 private static final class Row{final String label,value;final int color;Row(String l,String v,int c){label=l;value=v;color=c;}}
 private static final class SystemSnapshot{final String java=System.getProperty("java.version"),cpu=OpenGlHelper.getCpu(),os=System.getProperty("os.name")+" "+System.getProperty("os.arch"),vendor=safeGl(GL11.GL_VENDOR),renderer=safeGl(GL11.GL_RENDERER);}
 private static String safeGl(int n){String v=GL11.glGetString(n);return v==null?I18n.format("motionui.diagnostics.unknown"):v;}
 static final class FpsSampler{private final long[]frames=new long[180];private int count,index;private long last;void sample(long now){if(last!=0){frames[index]=Math.max(1,Math.min(1000000000L,now-last));index=(index+1)%frames.length;if(count<frames.length)count++;}last=now;}String summary(){if(count==0)return "—";long sum=0,max=0;for(int i=0;i<count;i++){sum+=frames[i];max=Math.max(max,frames[i]);}return(int)Math.round(1000000000D/(sum/(double)count))+" / "+(int)Math.round(1000000000D/max);}}
}
