package com.demonicrous.motionui.config;

import java.io.File;
import java.util.*;
import net.minecraftforge.common.config.Configuration;

public final class MotionUIConfig {
 public enum Policy{DEFAULT,ENABLED,DISABLED} public enum ScreenEasing{EASE_OUT_CUBIC,EASE_OUT_QUINT,EASE_IN_OUT_CUBIC} public enum ClosingMode{DISABLED,SIMPLIFIED,FULL} public enum BackgroundMode{AUTO,ANIMATED,STATIONARY,NONE} public enum CatalogSort{MOD_NAME,NAME,CONFIGURED,OBSERVED} public enum RuleSource{GLOBAL,MOD,CLASS} public enum DebugProfile{COMPACT,STANDARD,FULL}
 public enum AnimationStyle{SLIDE,SCALE,SCALE_SLIDE;public boolean hasSlide(){return this!=SCALE;}public boolean hasScale(){return this!=SLIDE;}}
 /** Direction in which an opening GUI travels towards its resting position. */
 public enum AnimationDirection{UP,DOWN,LEFT,RIGHT}
 public enum AnimationProfile{OFF(false,false,false,100,160,10,120,6),SUBTLE(true,true,true,80,110,4,90,3),SMOOTH(true,true,true,100,160,10,120,6),EXPRESSIVE(true,true,true,150,240,18,180,12),CUSTOM(true,true,true,100,160,10,120,6);final boolean h,c,x;final int hd,cd,co,xd,xo;AnimationProfile(boolean h,boolean c,boolean x,int hd,int cd,int co,int xd,int xo){this.h=h;this.c=c;this.x=x;this.hd=hd;this.cd=cd;this.co=co;this.xd=xd;this.xo=xo;}}
 public static final class ScreenRule{public final int duration,offset;public final ScreenEasing easing;public final AnimationStyle style;public final AnimationDirection direction;public ScreenRule(int d,int o,ScreenEasing e,AnimationStyle s,AnimationDirection a){duration=d;offset=o;easing=e;style=s;direction=a;}}
 public static final class ClosingRule{public final ClosingMode mode;public final int duration,offset;public final ScreenEasing easing;public final AnimationStyle style;public final AnimationDirection direction;public ClosingRule(ClosingMode m,int d,int o,ScreenEasing e,AnimationStyle s,AnimationDirection a){mode=m;duration=d;offset=o;easing=e;style=s;direction=a;}}
 private static Configuration config;public static boolean hotbar=true,containers=true,closing=true,modernDebug;public static int hotbarDuration=100,containerDuration=160,containerOffset=10,closingDuration=120,closingOffset=6;public static AnimationStyle containerStyle=AnimationStyle.SLIDE,closingStyle=AnimationStyle.SLIDE;public static AnimationDirection containerDirection=AnimationDirection.UP,closingDirection=AnimationDirection.UP;private static AnimationProfile profile=AnimationProfile.SMOOTH;private static ClosingMode closingMode=ClosingMode.SIMPLIFIED;private static DebugProfile debugProfile=DebugProfile.STANDARD;
 public static String catalogSearch="",catalogMod="all";public static CatalogSort catalogSort=CatalogSort.MOD_NAME;public static boolean catalogConfiguredOnly;public static int catalogScroll;
 private static final Map<String,Policy> policies=new HashMap<String,Policy>();private static final Map<String,ScreenRule> rules=new HashMap<String,ScreenRule>();private static final Map<String,ClosingRule> closingRules=new HashMap<String,ClosingRule>();private static final Map<String,BackgroundMode> backgroundModes=new HashMap<String,BackgroundMode>();
 private static final Map<String,Policy> modPolicies=new HashMap<String,Policy>();private static final Map<String,ScreenRule> modRules=new HashMap<String,ScreenRule>();private static final Map<String,ClosingRule> modClosingRules=new HashMap<String,ClosingRule>();private static final Map<String,BackgroundMode> modBackgroundModes=new HashMap<String,BackgroundMode>();private MotionUIConfig(){}
 public static synchronized void load(File f){config=new Configuration(f);config.load();hotbar=config.getBoolean("enabled","hotbar",true,"");hotbarDuration=config.getInt("durationMs","hotbar",100,40,400,"");modernDebug=config.getBoolean("modernF3","debug",false,"Use the MotionUI F3 information layout");try{debugProfile=DebugProfile.valueOf(config.getString("profile","debug","STANDARD",""));}catch(Exception ignored){debugProfile=DebugProfile.STANDARD;}containers=config.getBoolean("enabled","screens.containers",true,"");containerDuration=config.getInt("durationMs","screens.containers",160,0,400,"");containerOffset=config.getInt("offsetPx","screens.containers",10,0,32,"");containerStyle=parseStyle(config.getString("style","screens.containers","SLIDE",""));containerDirection=parseDirection(config.getString("direction","screens.containers","UP",""));closing=config.getBoolean("enabled","screens.closing",true,"");closingDuration=config.getInt("durationMs","screens.closing",120,0,300,"");closingOffset=config.getInt("offsetPx","screens.closing",6,0,24,"");closingStyle=parseStyle(config.getString("style","screens.closing","SLIDE",""));closingDirection=parseDirection(config.getString("direction","screens.closing","UP",""));if(config.hasKey("screens.closing","mode"))closingMode=parseMode(config.getString("mode","screens.closing","SIMPLIFIED",""));else{String old=config.getString("control","screens.closing","IMMEDIATE","");closingMode=!closing?ClosingMode.DISABLED:"AFTER_ANIMATION".equals(old)?ClosingMode.FULL:ClosingMode.SIMPLIFIED;}closing=closingMode!=ClosingMode.DISABLED;config.get("screens.closing","mode","SIMPLIFIED").set(closingMode.name());config.get("screens.closing","enabled",true).set(closing);
  boolean hp=config.hasKey("animations","profile");AnimationProfile requested=parseProfile(config.getString("profile","animations","SMOOTH","")),matching=matchingProfile();profile=!hp?matching:requested==AnimationProfile.CUSTOM||requested!=matching?AnimationProfile.CUSTOM:requested;config.get("animations","profile","SMOOTH").set(profile.name());
  policies.clear();for(String s:config.getStringList("classPolicies","compatibility",new String[0],"class=policy")){int i=s.lastIndexOf('=');if(i>0)try{policies.put(s.substring(0,i),Policy.valueOf(s.substring(i+1)));}catch(Exception ignored){}}
  rules.clear();for(String s:config.getStringList("classAnimations","compatibility",new String[0],"class|duration|offset|easing|style|direction")){Map.Entry<String,ScreenRule>e=parseScreenRule(s);if(e!=null)rules.put(e.getKey(),e.getValue());}
  closingRules.clear();for(String s:config.getStringList("classClosingAnimations","compatibility",new String[0],"class|mode|duration|offset|easing|style|direction")){Map.Entry<String,ClosingRule>e=parseClosingRule(s);if(e!=null)closingRules.put(e.getKey(),e.getValue());}
  backgroundModes.clear();for(String s:config.getStringList("classBackgroundModes","compatibility",new String[]{"thaumcraft.client.gui.GuiResearchBrowser=STATIONARY"},"class=background mode")){int i=s.lastIndexOf('=');if(i>0)try{backgroundModes.put(s.substring(0,i),BackgroundMode.valueOf(s.substring(i+1)));}catch(Exception ignored){}}
  modPolicies.clear();readEnumMap(config.getStringList("modPolicies","compatibility",new String[0],"mod=policy"),modPolicies,Policy.class);
  modRules.clear();for(String s:config.getStringList("modAnimations","compatibility",new String[0],"mod|duration|offset|easing|style|direction")){Map.Entry<String,ScreenRule>e=parseScreenRule(s);if(e!=null)modRules.put(e.getKey(),e.getValue());}
  modClosingRules.clear();for(String s:config.getStringList("modClosingAnimations","compatibility",new String[0],"mod|mode|duration|offset|easing|style|direction")){Map.Entry<String,ClosingRule>e=parseClosingRule(s);if(e!=null)modClosingRules.put(e.getKey(),e.getValue());}
  modBackgroundModes.clear();readEnumMap(config.getStringList("modBackgroundModes","compatibility",new String[0],"mod=background mode"),modBackgroundModes,BackgroundMode.class);
  catalogSearch=config.getString("search","catalog","","");catalogMod=config.getString("mod","catalog","all","");try{catalogSort=CatalogSort.valueOf(config.getString("sort","catalog","MOD_NAME",""));}catch(Exception e){catalogSort=CatalogSort.MOD_NAME;}catalogConfiguredOnly=config.getBoolean("configuredOnly","catalog",false,"");catalogScroll=config.getInt("scroll","catalog",0,0,Integer.MAX_VALUE,"");if(config.hasChanged())config.save();}
 public static synchronized Policy policy(String n){return policy(n,null);}public static synchronized Policy policy(String n,String mod){Policy p=policies.get(n);if(p!=null)return p;p=validMod(mod)?modPolicies.get(mod):null;return p==null?Policy.DEFAULT:p;}public static synchronized Policy ownPolicy(String n){Policy p=policies.get(n);return p==null?Policy.DEFAULT:p;}public static synchronized Policy modPolicy(String mod){Policy p=modPolicies.get(mod);return p==null?Policy.DEFAULT:p;}public static synchronized AnimationProfile profile(){return profile;}public static synchronized ClosingMode closingMode(){return closingMode;}public static synchronized boolean animationAllowed(Class<?>t){return animationAllowed(t.getName(),null);}public static synchronized boolean animationAllowed(String n){return animationAllowed(n,null);}public static synchronized boolean animationAllowed(String n,String mod){return policy(n,mod)!=Policy.DISABLED;}
 public static synchronized BackgroundMode backgroundMode(String n){BackgroundMode m=backgroundModes.get(n);return m==null?BackgroundMode.AUTO:m;}public static synchronized void setBackgroundMode(String n,BackgroundMode m){if(m==BackgroundMode.AUTO)backgroundModes.remove(n);else backgroundModes.put(n,m);saveBackgroundModes();}
 public static synchronized Policy cycle(String n){Policy p=policy(n),q=p==Policy.DEFAULT?Policy.ENABLED:p==Policy.ENABLED?Policy.DISABLED:Policy.DEFAULT;setPolicy(n,q);return q;}public static synchronized void setPolicy(String n,Policy p){if(p==Policy.DEFAULT)policies.remove(n);else policies.put(n,p);savePolicies();}
 public static synchronized ScreenRule rule(String n){return rule(n,null);}public static synchronized ScreenRule rule(String n,String mod){ScreenRule r=rules.get(n);if(r==null&&validMod(mod))r=modRules.get(mod);return r==null?globalRule():r;}public static synchronized ScreenRule modRule(String mod){ScreenRule r=validMod(mod)?modRules.get(mod):null;return r==null?globalRule():r;}public static synchronized ClosingRule closingRule(String n){return closingRule(n,null);}public static synchronized ClosingRule closingRule(String n,String mod){ClosingRule r=closingRules.get(n);if(r==null&&validMod(mod))r=modClosingRules.get(mod);return r==null?globalClosingRule():r;}public static synchronized ClosingRule modClosingRule(String mod){ClosingRule r=validMod(mod)?modClosingRules.get(mod):null;return r==null?globalClosingRule():r;}public static synchronized boolean hasRule(String n){return rules.containsKey(n);}public static synchronized boolean hasClosingRule(String n){return closingRules.containsKey(n);}public static synchronized boolean hasModRule(String mod){return modRules.containsKey(mod);}public static synchronized boolean hasModClosingRule(String mod){return modClosingRules.containsKey(mod);}public static synchronized RuleSource openingSource(String n,String mod){return rules.containsKey(n)||policies.containsKey(n)?RuleSource.CLASS:validMod(mod)&&(modRules.containsKey(mod)||modPolicies.containsKey(mod))?RuleSource.MOD:RuleSource.GLOBAL;}public static synchronized RuleSource closingSource(String n,String mod){return closingRules.containsKey(n)?RuleSource.CLASS:validMod(mod)&&modClosingRules.containsKey(mod)?RuleSource.MOD:RuleSource.GLOBAL;}public static synchronized boolean isConfigured(String n){return ownPolicy(n)!=Policy.DEFAULT||rules.containsKey(n)||closingRules.containsKey(n);}public static synchronized boolean isConfigured(String n,String mod){return isConfigured(n)||validMod(mod)&&(modPolicies.containsKey(mod)||modRules.containsKey(mod)||modClosingRules.containsKey(mod));}
 public static synchronized void setRule(String n,int d,int o,ScreenEasing e){ScreenRule r=rule(n);setRule(n,d,o,e,r.style,r.direction);}public static synchronized void setRule(String n,int d,int o,ScreenEasing e,AnimationStyle s,AnimationDirection a){rules.put(n,new ScreenRule(clamp(d,0,600),clamp(o,0,48),e,s,a));saveRules();}public static synchronized void setClosingRule(String n,ClosingMode m,int d,int o,ScreenEasing e){ClosingRule r=closingRule(n);setClosingRule(n,m,d,o,e,r.style,r.direction);}public static synchronized void setClosingRule(String n,ClosingMode m,int d,int o,ScreenEasing e,AnimationStyle s,AnimationDirection a){closingRules.put(n,new ClosingRule(m,clamp(d,0,600),clamp(o,0,48),e,s,a));saveClosingRules();}public static synchronized void resetOpening(String n){rules.remove(n);policies.remove(n);saveRules();savePolicies();}public static synchronized void resetClosing(String n){closingRules.remove(n);saveClosingRules();}public static synchronized void resetRule(String n){rules.remove(n);policies.remove(n);closingRules.remove(n);saveRules();savePolicies();saveClosingRules();}
 public static synchronized void setModPolicy(String mod,Policy p){requireMod(mod);if(p==Policy.DEFAULT)modPolicies.remove(mod);else modPolicies.put(mod,p);saveModPolicies();}public static synchronized void setModRule(String mod,int d,int o,ScreenEasing e,AnimationStyle s,AnimationDirection a){requireMod(mod);modRules.put(mod,new ScreenRule(clamp(d,0,600),clamp(o,0,48),e,s,a));saveModRules();}public static synchronized void setModClosingRule(String mod,ClosingMode m,int d,int o,ScreenEasing e,AnimationStyle s,AnimationDirection a){requireMod(mod);modClosingRules.put(mod,new ClosingRule(m,clamp(d,0,600),clamp(o,0,48),e,s,a));saveModClosingRules();}public static synchronized void resetModOpening(String mod){modRules.remove(mod);modPolicies.remove(mod);saveModRules();saveModPolicies();}public static synchronized void resetModClosing(String mod){modClosingRules.remove(mod);saveModClosingRules();}
 public static synchronized int applyOpening(Collection<String> names,ScreenRule rule,Policy policy){int count=0;for(String n:names)if(n!=null&&!n.isEmpty()){if(policy==Policy.DEFAULT)policies.remove(n);else policies.put(n,policy);rules.put(n,copy(rule));count++;}savePolicies();saveRules();return count;}public static synchronized int applyClosing(Collection<String> names,ClosingRule rule){int count=0;for(String n:names)if(n!=null&&!n.isEmpty()){closingRules.put(n,copy(rule));count++;}saveClosingRules();return count;}
 public static synchronized ClosingMode cycleClosingMode(){return cycleClosingMode(1);}public static synchronized ClosingMode cycleClosingMode(int direction){ClosingMode[]v=ClosingMode.values();closingMode=v[wrap(closingMode.ordinal()+(direction<0?-1:1),v.length)];closing=closingMode!=ClosingMode.DISABLED;profile=matchingProfile();saveProfile();return closingMode;}public static synchronized AnimationProfile cycleProfile(){return cycleProfile(1);}public static synchronized AnimationProfile cycleProfile(int direction){AnimationProfile[]v={AnimationProfile.OFF,AnimationProfile.SUBTLE,AnimationProfile.SMOOTH,AnimationProfile.EXPRESSIVE};int i=Arrays.asList(v).indexOf(profile);if(i<0)i=direction<0?0:v.length-1;AnimationProfile n=v[wrap(i+(direction<0?-1:1),v.length)];setProfile(n);return n;}public static synchronized void setProfile(AnimationProfile p){if(p==null||p==AnimationProfile.CUSTOM)return;profile=p;apply(p);saveProfile();}
 public static synchronized AnimationStyle cycleContainerStyle(int d){containerStyle=cycle(containerStyle,d);profile=matchingProfile();saveProfile();return containerStyle;}public static synchronized AnimationDirection cycleContainerDirection(int d){containerDirection=cycle(containerDirection,d);profile=matchingProfile();saveProfile();return containerDirection;}public static synchronized AnimationStyle cycleClosingStyle(int d){closingStyle=cycle(closingStyle,d);profile=matchingProfile();saveProfile();return closingStyle;}public static synchronized AnimationDirection cycleClosingDirection(int d){closingDirection=cycle(closingDirection,d);profile=matchingProfile();saveProfile();return closingDirection;}
 public static synchronized void setContainerMotion(AnimationStyle style,AnimationDirection direction){containerStyle=style;containerDirection=direction;profile=matchingProfile();saveProfile();}
 public static synchronized void setClosingMotion(AnimationStyle style,AnimationDirection direction){closingStyle=style;closingDirection=direction;profile=matchingProfile();saveProfile();}
 public static synchronized DebugProfile debugProfile(){return debugProfile;}public static synchronized void setModernDebug(boolean enabled){modernDebug=enabled;saveDebug();}public static synchronized DebugProfile cycleDebugProfile(){DebugProfile[]v=DebugProfile.values();debugProfile=v[(debugProfile.ordinal()+1)%v.length];modernDebug=true;saveDebug();return debugProfile;}public static synchronized void cycleDebugMode(){if(!modernDebug){modernDebug=true;debugProfile=DebugProfile.COMPACT;}else if(debugProfile==DebugProfile.FULL)modernDebug=false;else cycleDebugProfile();saveDebug();}private static void saveDebug(){if(config!=null){config.get("debug","modernF3",false).set(modernDebug);config.get("debug","profile","STANDARD").set(debugProfile.name());config.save();}}
 public static synchronized void saveCatalogState(String q,String m,CatalogSort s,boolean only,int scroll){catalogSearch=q;catalogMod=m;catalogSort=s;catalogConfiguredOnly=only;catalogScroll=Math.max(0,scroll);config.get("catalog","search","").set(q);config.get("catalog","mod","all").set(m);config.get("catalog","sort","MOD_NAME").set(s.name());config.get("catalog","configuredOnly",false).set(only);config.get("catalog","scroll",0).set(catalogScroll);config.save();}
 private static void savePolicies(){if(config==null)return;List<String>o=new ArrayList<String>();for(Map.Entry<String,Policy>e:policies.entrySet())o.add(e.getKey()+"="+e.getValue());Collections.sort(o);config.get("compatibility","classPolicies",new String[0]).set(o.toArray(new String[o.size()]));config.save();}private static void saveRules(){if(config==null)return;List<String>o=new ArrayList<String>();for(Map.Entry<String,ScreenRule>e:rules.entrySet()){ScreenRule r=e.getValue();o.add(e.getKey()+"|"+r.duration+"|"+r.offset+"|"+r.easing+"|"+r.style+"|"+r.direction);}Collections.sort(o);config.get("compatibility","classAnimations",new String[0]).set(o.toArray(new String[o.size()]));config.save();}private static void saveClosingRules(){if(config==null)return;List<String>o=new ArrayList<String>();for(Map.Entry<String,ClosingRule>e:closingRules.entrySet()){ClosingRule r=e.getValue();o.add(e.getKey()+"|"+r.mode+"|"+r.duration+"|"+r.offset+"|"+r.easing+"|"+r.style+"|"+r.direction);}Collections.sort(o);config.get("compatibility","classClosingAnimations",new String[0]).set(o.toArray(new String[o.size()]));config.save();}
 private static void saveModPolicies(){saveEnumMap("modPolicies",modPolicies);}private static void saveModRules(){saveScreenRuleMap("modAnimations",modRules);}private static void saveModClosingRules(){saveClosingRuleMap("modClosingAnimations",modClosingRules);}
 private static void saveBackgroundModes(){List<String>o=new ArrayList<String>();for(Map.Entry<String,BackgroundMode>e:backgroundModes.entrySet())o.add(e.getKey()+"="+e.getValue());Collections.sort(o);config.get("compatibility","classBackgroundModes",new String[0]).set(o.toArray(new String[o.size()]));config.save();}
 static Map.Entry<String,ScreenRule> parseScreenRule(String s){String[]p=s.split("\\|",6);if(p.length<4)return null;try{return new AbstractMap.SimpleImmutableEntry<String,ScreenRule>(p[0],new ScreenRule(clamp(Integer.parseInt(p[1]),0,600),clamp(Integer.parseInt(p[2]),0,48),ScreenEasing.valueOf(p[3]),p.length>=5?parseStyle(p[4]):AnimationStyle.SLIDE,p.length>=6?parseDirection(p[5]):AnimationDirection.UP));}catch(Exception ignored){return null;}}
 static Map.Entry<String,ClosingRule> parseClosingRule(String s){String[]p=s.split("\\|",7);if(p.length<5)return null;try{return new AbstractMap.SimpleImmutableEntry<String,ClosingRule>(p[0],new ClosingRule(ClosingMode.valueOf(p[1]),clamp(Integer.parseInt(p[2]),0,600),clamp(Integer.parseInt(p[3]),0,48),ScreenEasing.valueOf(p[4]),p.length>=6?parseStyle(p[5]):AnimationStyle.SLIDE,p.length>=7?parseDirection(p[6]):AnimationDirection.UP));}catch(Exception ignored){return null;}}
 private static ScreenRule globalRule(){return new ScreenRule(containerDuration,containerOffset,ScreenEasing.EASE_OUT_CUBIC,containerStyle,containerDirection);}private static ClosingRule globalClosingRule(){return new ClosingRule(closingMode,closingDuration,closingOffset,ScreenEasing.EASE_OUT_CUBIC,closingStyle,closingDirection);}private static ScreenRule copy(ScreenRule r){return new ScreenRule(r.duration,r.offset,r.easing,r.style,r.direction);}private static ClosingRule copy(ClosingRule r){return new ClosingRule(r.mode,r.duration,r.offset,r.easing,r.style,r.direction);}
 private static boolean validMod(String mod){return mod!=null&&!mod.isEmpty()&&!"all".equals(mod)&&!"unknown".equals(mod);}private static void requireMod(String mod){if(!validMod(mod))throw new IllegalArgumentException("A known mod id is required");}
 private static <E extends Enum<E>>void readEnumMap(String[] values,Map<String,E> target,Class<E> type){for(String s:values){int i=s.lastIndexOf('=');if(i>0)try{target.put(s.substring(0,i),Enum.valueOf(type,s.substring(i+1)));}catch(Exception ignored){}}}
 private static <E extends Enum<E>>void saveEnumMap(String key,Map<String,E> values){if(config==null)return;List<String>o=new ArrayList<String>();for(Map.Entry<String,E>e:values.entrySet())o.add(e.getKey()+"="+e.getValue());Collections.sort(o);config.get("compatibility",key,new String[0]).set(o.toArray(new String[o.size()]));config.save();}
 private static void saveScreenRuleMap(String key,Map<String,ScreenRule> values){if(config==null)return;List<String>o=new ArrayList<String>();for(Map.Entry<String,ScreenRule>e:values.entrySet()){ScreenRule r=e.getValue();o.add(e.getKey()+"|"+r.duration+"|"+r.offset+"|"+r.easing+"|"+r.style+"|"+r.direction);}Collections.sort(o);config.get("compatibility",key,new String[0]).set(o.toArray(new String[o.size()]));config.save();}
 private static void saveClosingRuleMap(String key,Map<String,ClosingRule> values){if(config==null)return;List<String>o=new ArrayList<String>();for(Map.Entry<String,ClosingRule>e:values.entrySet()){ClosingRule r=e.getValue();o.add(e.getKey()+"|"+r.mode+"|"+r.duration+"|"+r.offset+"|"+r.easing+"|"+r.style+"|"+r.direction);}Collections.sort(o);config.get("compatibility",key,new String[0]).set(o.toArray(new String[o.size()]));config.save();}
 static synchronized void resetForTests(){config=null;modernDebug=false;debugProfile=DebugProfile.STANDARD;policies.clear();rules.clear();closingRules.clear();backgroundModes.clear();modPolicies.clear();modRules.clear();modClosingRules.clear();modBackgroundModes.clear();}
 private static AnimationProfile parseProfile(String v){try{return AnimationProfile.valueOf(v);}catch(Exception e){return AnimationProfile.CUSTOM;}}private static ClosingMode parseMode(String v){try{return ClosingMode.valueOf(v);}catch(Exception e){return ClosingMode.SIMPLIFIED;}}private static AnimationStyle parseStyle(String v){try{return AnimationStyle.valueOf(v);}catch(Exception e){return AnimationStyle.SLIDE;}}private static AnimationDirection parseDirection(String v){try{return AnimationDirection.valueOf(v);}catch(Exception e){return AnimationDirection.UP;}}private static AnimationProfile matchingProfile(){for(AnimationProfile p:AnimationProfile.values())if(p!=AnimationProfile.CUSTOM&&matches(p))return p;return AnimationProfile.CUSTOM;}private static boolean matches(AnimationProfile p){return hotbar==p.h&&containers==p.c&&closing==p.x&&hotbarDuration==p.hd&&containerDuration==p.cd&&containerOffset==p.co&&closingDuration==p.xd&&closingOffset==p.xo&&containerStyle==AnimationStyle.SLIDE&&closingStyle==AnimationStyle.SLIDE&&containerDirection==AnimationDirection.UP&&closingDirection==AnimationDirection.UP;}private static void apply(AnimationProfile p){hotbar=p.h;containers=p.c;closing=p.x;if(!closing)closingMode=ClosingMode.DISABLED;else if(closingMode==ClosingMode.DISABLED)closingMode=ClosingMode.SIMPLIFIED;hotbarDuration=p.hd;containerDuration=p.cd;containerOffset=p.co;closingDuration=p.xd;closingOffset=p.xo;containerStyle=closingStyle=AnimationStyle.SLIDE;containerDirection=closingDirection=AnimationDirection.UP;}private static void saveProfile(){config.get("animations","profile","SMOOTH").set(profile.name());config.get("hotbar","enabled",true).set(hotbar);config.get("hotbar","durationMs",100).set(hotbarDuration);config.get("screens.containers","enabled",true).set(containers);config.get("screens.containers","durationMs",160).set(containerDuration);config.get("screens.containers","offsetPx",10).set(containerOffset);config.get("screens.containers","style","SLIDE").set(containerStyle.name());config.get("screens.containers","direction","UP").set(containerDirection.name());config.get("screens.closing","enabled",true).set(closing);config.get("screens.closing","durationMs",120).set(closingDuration);config.get("screens.closing","offsetPx",6).set(closingOffset);config.get("screens.closing","style","SLIDE").set(closingStyle.name());config.get("screens.closing","direction","UP").set(closingDirection.name());config.get("screens.closing","mode","SIMPLIFIED").set(closingMode.name());config.save();}private static int wrap(int v,int size){int r=v%size;return r<0?r+size:r;}private static int clamp(int v,int a,int b){return Math.max(a,Math.min(b,v));}
 private static AnimationStyle cycle(AnimationStyle v,int d){AnimationStyle[]a=AnimationStyle.values();return a[wrap(v.ordinal()+(d<0?-1:1),a.length)];}private static AnimationDirection cycle(AnimationDirection v,int d){AnimationDirection[]a=AnimationDirection.values();return a[wrap(v.ordinal()+(d<0?-1:1),a.length)];}
}
